### ISSUE TITLE
程序开发资料大集

### ISSUE THREAD

**Issue by hunshiouren** [hunshiouren/KidWeChat#2]
大家可以在这里随便发程序开发方面相关的资料，积攒多了以后再分类整理进入 wiki O(∩_∩)O~

**Comment by hunshiouren** [comment]
[微信公众平台 Python 开发包文档](http://wechat-python-sdk.readthedocs.io)

**Comment by BravoCiao** [comment]
[Branding Strategy](http://www.slideshare.net/lipmanhearne/developing-a-brand-strategy)

**Comment by hunshiouren** [comment]
[微信个人号接口：itchat](https://itchat.readthedocs.io/zh/latest/)
[使用案例：手把手教你利用个人微信号 API（微信控制器、群发助手、好友删除检测）](https://www.v2ex.com/t/312917)
[Python微信库:itchat](http://www.tuicool.com/articles/VJZRRfn)

**Comment by draachen** [comment]
基于Python2.7，SAE，图灵API的微信文字聊天机器人：  
参考[“零基础 20 分钟搭建 SAE 微信个人号后台”](http://python.jobbole.com/84967/) 及[“视频”](http://v.youku.com/v_show/id_XMTU1NjA0NDIwMA==)即可创建属于自己的微信聊天机器人

**Comment by hunshiouren** [comment]
itchat：发送给指定的联系人或群（[link](http://zhanghonglun.cn/blog/project/基于itchat实现微信群消息同步机器人/?hmsr=toutiao.io&utm_medium=toutiao.io&utm_source=toutiao.io)）

**Comment by windflyinglx** [comment]
[微信公众号平台开发教程](http://www.cnblogs.com/txw1958/)

**Comment by draachen** [comment]
#工作进展# 2017/03/12 19:35  

微信+SAE+Python2.7实现微信自动回复：  

	根据接收到的消息类型，返回文本信息：This is a text，image or voice, etc

![image](https://github.com/draachen/Py103/blob/master/Chap8/2017-03-12_16h51_12.png?raw=True)

云服务器选择:SAE

选用Python2.7是由于现成的[资料](http://www.bilibili.com/video/av8420181/index_6.html)涉及web.py模块，Python3不支持web.py模块。当然也可以选用Python3，然后使用Flask等框架。

选择Python共享服务器，应用配置文件config.yaml和代码配置文件index.wsgi。其实也可以选择云容器的独享服务器，配置requirements.txt,runtime.txt以及Procfile(参考Py103Chap6部署到Heroku任务)

代码调试使用ngrok国内免费服务器。
每次更改本地代码查看效果，需push到云服务器然后通过微信交互验证代码是否ok，且本地运行脚本无法接收到微信端服务器的请求。遂搜索之["微信开发如何做本地调试？"](https://www.zhihu.com/question/25456655)，了解到ngrok。试用之发现ngrok的官方网页国内访问太慢，故重新搜索，选用“[汉化的ngrok](http://qydev.com/)”。

**Comment by BravoCiao** [comment]
[itchat API列表](http://itchat.readthedocs.io/zh/latest/api/)
