### ISSUE TITLE
项目思路梳理

### ISSUE THREAD

**Issue by hunshiouren** [hunshiouren/KidWeChat#3]
上周在课程仓库发的项目报名，实在是太粗糙了...不忍直视... 在 @luckysilly  引导帮助下重新梳理了想法。
希望这个梳理做一个引子，大家一起讨论，使得项目的目标、内容、如何操作更明确，也便于后面再讨论具体的分工~

大家有任何想法，可随时回复在这个 issue 下或群里~

1. 为什么要做
	* 幼儿进入幼儿园开始更广泛的社交后，难免会使用微信与小朋友、老师、家人进行互动，而现在的微信是基于成人网络社交设计，希望做一个端口，使得基于微信的社交过程对幼儿更加友好。
	* 在幼儿使用微信互动时，因为幼儿识字量有限，家长总是需要在旁边提供辅助，一方面干扰了幼儿社交过程，另一方面占用了家长的时间、精力。
	* 家长一方面难以避免幼儿使用电子设备，另一方面又十分担心幼儿会沉迷于电子设备，要防止儿童使用时间过长。 
     * 除了幼儿，微信使用对于有阅读障碍的人士也存在障碍。

2. 想实现什么
	* 将幼儿常用联系人、公众号汇总在一起，突出常用功能（语音、视频、表情），易于发现使用
	* 用图片、语音等设计手段替代文字标示，减少文字造成的障碍
	* 防沉迷功能：使用时间多于一定标准，则发送提示且不能再继续使用
	* （理想）根据儿童的情绪类型给予相应的视觉设计反馈，帮助儿童疏导认知自己的情绪

3. 怎么去做
	* 平台选择：订阅号？公众号？小程序？
	* 后台接口：获得家长微信联系人、公众号的接口？跳转信息详情页的接口？如果以上两个接口没有，是否有替代接口以及替代的实现方式？（发起语音、视频的接口是否有？）
	* 前端接口和代码：订阅号或公众号是否有接口改变视觉设计？如何没有，以何种方式实现视觉引导？如果选择小程序，前端怎么写？ HTML + CSS？
   * 多用户登陆：数据库如何实现？数据库选择，使用 SQLAlchemy( flask_sqlalchemy) ?（部署平台？）
   * 协作：如何保障 ALL KNOW ALL（项目团队内、py103） ？不同模块，多人共同编程，如何协作（变量名、方法名、逻辑过程说明）？不同的模块，怎么组合成产品？ 

粗糙原始注册流程：
![](https://raw.githubusercontent.com/hunshiouren/Py103/master/Chap8/note/kidwechat-%E6%B3%A8%E5%86%8C%E6%B5%81%E7%A8%8B%E5%9B%BE.png?token=AL6ua5MpicvEwcWn7CPRj-Jp7Jyl7URpks5YxkElwA%3D%3D)

粗糙原始版使用流程：
![](https://raw.githubusercontent.com/hunshiouren/Py103/master/Chap8/note/kidwechat-%E4%BD%BF%E7%94%A8%E6%B5%81%E7%A8%8B%E5%9B%BE.png?token=AL6ua3LGqNedLn3UIKqhKsdGLM5aVICmks5YxkFWwA%3D%3D)

**Comment by BravoCiao** [comment]
结合1.为什么要做&2.想实现什么，我细致分析了一下我们的项目

我们想实现的：

- 将幼儿常用联系人、公众号汇总在一起

** 我的想法：这个只要幼儿有自己的微信号和手机就可以实现 **

*** 痛点：大多数幼儿没有自己的手机，无法实现信息分流，需要一款额外的应用把幼儿的联系人、公众号和父母的分开，维护幼儿的独立意识 ***

*** 疑问：即使幼儿有自己的微信号了，使用公众号阅读故事依然需要父母从旁协助，还是会占用父母精力。***

————————————————————————————————————————————————
- 突出常用功能（语音、视频、表情），易于发现使用，用图片、语音等设计手段替代文字标示，减少文字造成的障碍 

*** 痛点：幼儿识字数量少，现有的微信界面对儿童不够友好 ***

*** 疑问：目前来看，主要社交手段是语音和视频，不包括图片，图片只是辅助幼儿找到语音/视频标志的工具。***
————————————————————————————————————————————————

- 防沉迷功能：使用时间多于一定标准，则发送提示且不能再继续使用 

- （理想）根据儿童的情绪类型给予相应的视觉设计反馈，帮助儿童疏导认知自己的情绪

————————————————————————————————————————————————
### 有没有可能界面能够加上简单的游戏，辅助内向的小孩子破冰？自己写游戏代码？引入游戏页面？如果技术上太难实现就把程序做成针对外向、独立意识强、社交能力强的小孩吧。

**Comment by BravoCiao** [comment]
### 怎么去做梳理

- 平台选择：订阅号？服务号？小程序？

根据李明教练给的建议，小程序探索预计要花一个星期，时间上等不起，剔除。~~小程序~~
订阅号 VS 服务号
服务号有高级接口( 对应视频、语音的功能&其他功能 )&自定义菜单( 界面美化 )
因为李欣的朋友有废弃的服务号不用，就敲定使用服务号
##### 最终选择：服务号

- 后台接口：

  - 获得家长微信联系人、公众号的接口？
   itchat有
  - 跳转信息详情页的接口？
   待查
  - *发起语音、视频的接口？*

- 前端接口和代码：订阅号或公众号是否有接口改变视觉设计？如何没有，以何种方式实现视觉引导？如果选择小程序，前端怎么写？ HTML + CSS？
视觉设计先暂时不考虑了，最后颜值不够，PPT来凑。
- *多用户登陆：数据库如何实现？数据库选择，使用 SQLAlchemy( flask_sqlalchemy) ?（部署平台？）*

- 协作：
  - 如何保障 ALL KNOW ALL（项目团队内、py103） ？
每个星期两次视频会议(暂定周三&周六/日)，会议上做好分工之后，Bravo会在当天开一个issue作总结&做跟踪，各自在issue上发表进度展示/感想。
因为每次开完视频会议都会开新的issue，每个issue的有效期是两次视频会议之间。
Py103暂时不必理会   
  - 不同模块，多人共同编程，如何协作（变量名、方法名、逻辑过程说明）？
逻辑过程说明会画流程图演示。
变量名、方法名在写出代码后讨论后统一。
  - *不同的模块，怎么组合成产品？*
