### ISSUE TITLE
Week0Dday7_项目梳理&下周MVP目标制定&进度跟踪

### ISSUE THREAD

**Issue by BravoCiao** [hunshiouren/KidWeChat#4]
(170326) 开始 结业项目路演、 结业典礼
## 项目倒计时：14天

- ### Part.1-主轴梳理：

我觉着我们这个项目最大的卖点是：
### 信息分流+语音识别
要抓住这两个点。
### 如果本周的MVP可以做起来，就能初步实现信息分流。虽然可以直接从父母的微信联系人列表里，搜索联系人进行语音/视频，做一个服务号实现这个功能看似多此一举，但通过这个步骤能建立起幼儿的领地意识。和长大了要有自己的房间是一个概念，只不过这个是针对数位原始人世代推出的虚拟房间。

幼儿不能识字，语音识别可以做成是最好最好的，
朋辈社交：语音+语音，
幼儿和长辈的社交：语音+文字，
幼儿输入的语音转化成文字输出给长辈，
长辈输入的文字转换成语音输出给幼儿/长辈直接输出语音给幼儿。

————————————————————————————————————————————————
- ### Part.2-技术细节：
本周MVP：

- Path 1：鸡腿和李欣探索python3+itchat
  - Step 1：用itchat写出用于给幼儿分拣信息的微信机器人
     MVP_1：先添加联系人，写进字典里面，再从字典里调取联系人发信息
     MVP_2：MVP1实现了之后，尝试从父母的微信联系人列表里直接搜索调取，即：不写字典
  - Step 2：itchat接口部署到服务号上
 
- Path 2：Ramsey探索python2.7+web.py模块

周三晚8点汇报项目进度

————————————————————————————————————————————————
### 我理解的itchat流程：

1. 扫码登陆自己的微信

2. 得到微信里所有的联系人列表
对应API：
def get_friends(self, update=False):
    ''' fetch friends list
        for options
            - update: if not set, local value will be returned
        for results
            - a list of friends' info dicts will be returned
        it is defined in components/contact.py

  3.从联系人列表里选择要添加的联系人并添加friend's info进字典
对应API:
def search_friends(self, name=None, userName=None, remarkName=None, nickName=None,
        wechatAccount=None):
    return self.storageClass.search_friends(name, userName, remarkName,
        nickName, wechatAccount)

def add_friend(self, userName, status=2, verifyContent='', autoUpdate=True):
    ''' add a friend or accept a friend
        for options
            - userName: 'UserName' for friend's info dict
            - status:
                - for adding status should be 2
                - for accepting status should be 3
            - ticket: greeting message
            - userInfo: friend's other info for adding into local storage
        it is defined in components/contact.py
    '''
    raise NotImplementedError()
  4.选择联系人一对一联络，发消息、视频、图片之类之类
————————————————————————————————————————————————
### 我的疑问
1.为什么要纠结userid？代码里面对应的toUserName是对应什么？我看官网上的解释，说是用备注、微信号和昵称都可以找到联系人的
![](https://cloud.githubusercontent.com/assets/23642700/23837077/6d5d04b0-07bd-11e7-9b0f-78722af0f05b.png)

2.上面图片的最后一行，是可以获取公众号的，那我们其实是可以把公众号汇总到联系人列表里面的对吧？我在API列表里面看到了这两个：
def get_mps(self, update=False):
    ''' fetch massive platforms list
        for options
            - update: if not set, local value will be returned
        for results
            - a list of platforms' info dicts will be returned
        it is defined in components/contact.py
    '''
    raise NotImplementedError()

def get_contact(self, update=False):
    ''' fetch part of contact
        for part
            - all the massive platforms and friends are fetched
            - if update, only starred chatrooms are fetched
        for options
            - update: if not set, local value will be returned
        for results
            - chatroomList will be returned
        it is defined in components/contact.py
    '''
    raise NotImplementedError()
公众号是当做朋友添加的吗？

3.假教是从哪里看出来send_video那个API可能没实现的？raise NotImplementedError()不是每个API后面都有这一行吗？

**Comment by hunshiouren** [comment]
先说下抱歉....... 自己又走上了课程前期的老路，不动手、对内容视而不见...... 才导致昨天讨论时，虽然知道可以实现，但很多问题给不出明确的答案...... 造成不能根据 itchat 的接口梳理出靠谱、清晰的逻辑与思路......

 自己这两天下班后会把 itchat  中可能涉及的函数都尝试一遍，努力在周三前，梳理清晰的调用情况。
——————————————————————————————————————————————
### MVP 补充
- 无论使用什么库，都需要实现的最最基本思路：
获取某个联系人的 id —— 将 id 写入list or dict (先不用数据库) —— 查找联系人（“我要找 xx”）—— 反馈：开始和 xx 聊天吧 / 没有找到 xx —— 聊天（公众号内需要发信人的名字提示，“小明：...” ）—— 结束聊天


- itchat 尝试实现：（待确定和梳理）
    - itchat 的实现逻辑，目前想的和 bravo 整理的一样
    - 会把相关函数都尝试一遍，看一下调用的反馈结果，确定逻辑


- 公众号尝试实现：
    - @draachen 你提的一些想法，我现在才完全反应过来...... 首先，确实如果只是上面这个最最基本思路，公众号已有的接口已全部可以实现，不需要用其他接口。就是让公众号做个枢纽，使得关注者之间互相通信。
    - 其次，如果用公众号，是像你提到的需要使用数据库。而且至少两张数据表。一张是关注用户的 id 表，另一张是每个用户对应的联系人表。

**Comment by hunshiouren** [comment]
> 1.为什么要纠结userid？代码里面对应的toUserName是对应什么？我看官网上的解释，说是用备注、微信号和昵称都可以找到联系人的

因为如果使用公众号，发送信息使用的是 id，不是微信号或昵称。昨晚，假教尝试，确定 itchat 则是可以直接使用微信号发送信息。这个纠结，应该是当时，两种思路搅在了一起，并且没有尝试代码，所开始以为 itchat 和公众号一样需要用到 id ，直到教练尝试了才知道用微信号就好......（发现 动手、不要视而不见 是那么的朴素而实用！）

> 2.上面图片的最后一行，是可以获取公众号的，那我们其实是可以把公众号汇总到联系人列表里面的对吧？我在API列表里面看到了这两个：

现在不确定这个公众号搜索返回的数据是什么。如果搜索反馈的只是公众号的名称、id 这些，就只能给公众号发信息，实现小朋友可以给公众号留言，但不能跳转进入公众号。

> 3.假教是从哪里看出来send_video那个API可能没实现的？raise NotImplementedError()不是每个API后面都有这一行吗？

我理解假教的建议是，这个库里面提到的接口建议都直接尝试一遍。因为不确定作者是真的用接口实现了功能，还是只是写了个函数放在那里留个位置。所以虽然有 send_video，但没试过就不能确定是可用的。
