### ISSUE TITLE
itchat资料包

### ISSUE THREAD

**Issue by BravoCiao** [hunshiouren/KidWeChat#5]
关于itchat的资料开始变多、变杂了，新开一个issue进行归档
有新的资料可以在下面跟帖，积攒到一定程度整理进wiki
[itchat项目简介](https://itchat.readthedocs.io/zh/latest/)
[itchat API](http://itchat.readthedocs.io/zh/latest/api/)
[Python微信库:itchat](http://www.tuicool.com/articles/VJZRRfn)
[基于Itchat实现微信群消息同步机器人](http://zhanghonglun.cn/blog/project/%E5%9F%BA%E4%BA%8Eitchat%E5%AE%9E%E7%8E%B0%E5%BE%AE%E4%BF%A1%E7%BE%A4%E6%B6%88%E6%81%AF%E5%90%8C%E6%AD%A5%E6%9C%BA%E5%99%A8%E4%BA%BA/?hmsr=toutiao.io&utm_medium=toutiao.io&utm_source=toutiao.io)
[手把手教你利用个人微信号 API（微信控制器、群发助手、好友删除检测）](https://www.v2ex.com/t/312917)

**Comment by BravoCiao** [comment]
### itchat已有接口：
登陆、生成二维码的接口先略过
- 获取关注列表联系人、公众号
- 发送文字、图片、视频(视频接口不知道能不能用)
### 待探索接口：
- 跳转到公众号的接口
由于不确定itchat里，搜索公众号返回的数据是什么。如果只是公众号名称、id，就只能给公众号发消息，不能跳转到公众号。
- 发起语音、视频的接口

**Comment by hunshiouren** [comment]
目前我们的逻辑虽然确定了，但是用代码如何实现还在探索，上 3月13日 itchat 代码笔记：[link](https://github.com/hunshiouren/Py103/blob/0c9e8f2510601c708d536b74aced76d0ec1a4362/Chap9/note/itchat-note.ipynb)。

* 看到了语音和视频的接口，案例中也有语音转发的代码，那个代码尝试了，可以实现语音的转发。
* 尝试了有获取联系人、群聊的函数，没有发现获取公众号的函数... 自己再看看，不行去骚扰教练们

**Comment by BravoCiao** [comment]
注：这些接口只能发送文字、图片、语音、视频
而不能进行语音和视频通话

**Comment by hunshiouren** [comment]
3.14 探索汇报

* create_chatroom 创建群聊失败，已到 itchat 仓库发了 [issue](https://github.com/littlecodersh/ItChat/issues/280)。今晚再看看。
* 昨晚的笔记 commit 忘记同步了..... 今天下班后补上

**Comment by hunshiouren** [comment]
[完整笔记](https://github.com/hunshiouren/Py103/blob/master/Chap9/note/itchat-note.ipynb)
