### ISSUE TITLE
机器人问题汇总

### ISSUE THREAD

**Issue by hunshiouren** [hunshiouren/KidWeChat#7]
每天晚上 8:00-11:30 机器人上线

机器人使用过程遇到问题，可直接回复在这个 issue。

@windflyinglx @draachen 修改并 push 过的问题，请在问题的 comment 内写明修改时间、修改人。如：鸡腿儿，3.18 已修订。不确定如何修改的问题，咱们群中讨论。

**Comment by windflyinglx** [comment]
问题：迟迟不显示二维码
问题描述：一分钟之内未显示二维码，而马上换其他测试文件却可以显示，排除网络问题。
解决方法：对比无法显示二维码和可以显示的两类文件，将bot = Bot(cache_path=True)改为bot = Bot()，bot.start(block=True)改为bot.start()，二维码又现身了＝ ＝
鸡腿儿（这个名字真顺口啊。。。）3.18 已修订

**Comment by windflyinglx** [comment]
问题：在第二次运行代码搜索相同群名时，会出现List index error
描述：例如，代码 group = bot.groups().search('ABC')[0]，搜索群名为ABC的群，第一次运行完全没问题，第二次运行会出现List index error，但代码并未更改。
暂时的解决方法：如果是群主，修改群名...如果不是，换一个群...惹不起躲得起...
鸡腿儿 3.18 已修订
